name: CI
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/setup-python@master
      with:
        python-version: 3.7
    - run: make prepare
    # Create empty command dir for later missing command testing
    - run: mkdir scripts/commands/awsinfo
    - run: make test
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: make shellcheck || exit 0