name: unit-tests
on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * 1"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-python@master
      - run: make prepare
      # Create empty command dir for later missing command testing
      - run: mkdir scripts/commands/awsinfo
      - run: make test
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: make shellcheck || exit 0
  docker:
    runs-on: ubuntu-latest
    needs: unit-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: theserverlessway/awsinfo:latest
          cache-from: type=registry,ref=theserverlessway/awsinfo:buildcache
          cache-to: type=registry,ref=theserverlessway/awsinfo:buildcache,mode=max